[app]
port = 8796
env = "development"
secret = "MbeYEuMWgrcLt4KW7BujdwCb9cmBk7CV"
expiry = "336h"

[log]
level = "debug"

[db.postgres]
host="localhost"
port="5432"
user="postgres"
password="postgres"
database="simplejwt"