[app]
port = 8796
env = "development"
secret = "V49nnkk0NJCfW5EQMCINNClwNA4sq7ux"
expiry = "336h"

[log]
level = "debug"

[db.postgres]
host="localhost"
port="5432"
user="postgres"
password="postgres"
database="simplejwt"